CREATE TABLE ERS_USERS (
USER_ID INT PRIMARY KEY,
USERNAME VARCHAR2(20) NOT NULL UNIQUE,
USER_PASSWORD VARCHAR2(20) NOT NULL
);

CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT PRIMARY KEY,
USER_ID INT NOT NULL UNIQUE,
FOREIGN KEY (USER_ID) REFERENCES ERS_USERS(USER_ID)
);

CREATE TABLE REIMBURSEMENT_REQUESTS (
REQUEST_ID NUMBER PRIMARY KEY,
EMPLOYEE_ID INT NOT NULL,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
AMOUNT NUMBER(*,2) NOT NULL,
REQUEST_DATE DATE,
DESCIPTION NVARCHAR2(100),
APPROVED INT
);

CREATE TABLE MANAGERS (
MANAGER_ID INT PRIMARY KEY,
USER_ID INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES ERS_USERS(USER_ID)
);

CREATE SEQUENCE SEQ_USER_ID;
CREATE SEQUENCE SEQ_EMPLOYEE_ID;
CREATE SEQUENCE SEQ_REQUEST_ID;
CREATE SEQUENCE SEQ_MANAGER_ID;

CREATE PROCEDURE PROC_INSERT_EMPLOYEE (P_USERNAME IN ERS_USERS.USERNAME%TYPE, P_PASSWORD IN ERS_USERS.USER_PASSWORD%TYPE)
AS
N_NEXT_USER_ID ERS_USERS.USER_ID%TYPE;
BEGIN
  N_NEXT_USER_ID := SEQ_USER_ID.NEXTVAL;
  INSERT INTO ERS_USERS VALUES(N_NEXT_USER_ID, P_USERNAME, P_PASSWORD);
  INSERT INTO EMPLOYEES VALUES(SEQ_EMPLOYEE_ID.NEXTVAL, N_NEXT_USER_ID);
END PROC_INSERT_EMPLOYEE;