CREATE TABLE ERS_USERS (
USER_ID INT PRIMARY KEY,
USERNAME VARCHAR2(20) NOT NULL UNIQUE,
USER_PASSWORD VARCHAR2(20) NOT NULL
);

CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT PRIMARY KEY,
USER_ID INT NOT NULL UNIQUE,
FOREIGN KEY (USER_ID) REFERENCES ERS_USERS(USER_ID)
);

CREATE TABLE REIMBURSEMENT_REQUESTS (
REQUEST_ID NUMBER PRIMARY KEY,
EMPLOYEE_ID INT NOT NULL,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
AMOUNT NUMBER(*,2) NOT NULL,
REQUEST_DATE DATE,
DESCIPTION NVARCHAR2(100),
APPROVED INT
);

CREATE TABLE MANAGERS (
MANAGER_ID INT PRIMARY KEY,
USER_ID INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES ERS_USERS(USER_ID)
);